### ISSUE TITLE
Problem with convert

### ISSUE THREAD

**Issue by artekw** [machinekoder/NGCWriter#4]
I try convert gcode from PrusaSlic3r 2.2 for Marlin

`Traceback (most recent call last):
  File "convert_gcode.py", line 34, in <module>
    gcodeConverter.process(gcode_list)
  File "/home/artek/Pulpit/NGCWriter/converter/gcode2ngc.py", line 54, in process
    data = self.process_layer(data)
  File "/home/artek/Pulpit/NGCWriter/converter/gcode2ngc.py", line 41, in process_layer
    data = self.do_regex_replacements(data)
  File "/home/artek/Pulpit/NGCWriter/converter/gcode2ngc.py", line 33, in do_regex_replacements
    line = regex.sub(replacement, line)
TypeError: expected string or bytes-like object
`

**Comment by the-snowwhite** [comment]
I'm getting a similar error:

        $python3.5 ./convert_gcode.py -i PI3MIBDEV_circle_30_40x10.gcode -o PI3MIBDEV_circle_30_40x10.ngc
    converting PI3MIBDEV_circle_30_40x10.gcode -> PI3MIBDEV_circle_30_40x10.ngc
    Traceback (most recent call last):
    File "./convert_gcode.py", line 34, in <module>
        gcodeConverter.process(gcode_list)
    File "/work/converter/gcode2ngc.py", line 54, in process
        data = self.process_layer(data)
    File "/work/converter/gcode2ngc.py", line 41, in process_layer
        data = self.do_regex_replacements(data)
    File "/work/converter/gcode2ngc.py", line 33, in do_regex_replacements
        line = regex.sub(replacement, line)
    TypeError: expected string or bytes-like object
    runner@32c0e255be1b:/work$
